A pipeline will run my experiment on a specialized Kubernetes pod on each push

diff --git a/.github/workflows/mlops.yaml b/.github/workflows/mlops.yaml
--- a/.github/workflows/mlops.yaml
+++ b/.github/workflows/mlops.yaml
@@ -18,41 +18,68 @@ permissions:
   id-token: write
 
 jobs:
-  train-and-report:
-    permissions: write-all
-    runs-on: self-hosted
+  setup-runner:
+    runs-on: [self-hosted, base-runner]
     if: github.event_name == 'pull_request'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+      - name: Login to Google Cloud
+        uses: google-github-actions/auth@v2 with:
+          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
+      - name: Get Google Cloud's Kubernetes credentials
+        uses: google-github-actions/get-gke-credentials@v2 with:
+          cluster_name: ${{ secrets.GCP_K8S _CLUSTER_NAME }} location: ${{
+          secrets.GCP_K8S_CLUSTER _ZONE }}
+      - name: Set up GCloud SDK
+        uses: google-github-actions/setup-gcloud@v2 with:
+          version: '>= 494.0.0'
+      - name: Install kubectl
+        run: |
+          gcloud components install kubectl
+      - name: Install gke-gcloud-auth-plugin
+        run: |
+          gcloud components install gke-gcloud-auth-plugin
+      - name: Initialize runner on Kubernetes
+        env:
+          KUBECONFIG_DATA: ${{ secrets.GCP_K8S_KUBECONFIG }}
+        # We use envsubst to replace variables in runner-gpu.yaml
+        # in order to create a unique runner name with the
+        # GitHub run ID. This prevents conflicts when multiple
+        # runners are created at the same time.
+        run: |
+          echo "$KUBECONFIG_DATA" > kubeconfig export KUBECONFIG=kubeconfig
+          # We use run_id to make the runner name unique
+          export GITHUB_RUN_ID="${{ github.run_id }}" envsubst <
+          kubernetes/runner-gpu.yaml | kubectl apply -f -
+  train-and-report:
+    permissions: write-all
+    needs: setup-runner
+    runs-on: [self-hosted, gpu-runner]
+    if: github.event_name == 'pull_request' steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
       - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.11"
-          cache: pip
+        uses: actions/setup-python@v5 with:
+          python-version: '3.11' cache: pip
       - name: Install dependencies
         run: pip install --requirement requirements-freeze.txt
       - name: Login to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
-          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
+        uses: google-github-actions/auth@v2 with:
+          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
       - name: Train model
         run: dvc repro --pull
       - name: Push the outcomes to DVC remote storage
         run: dvc push
       - name: Commit changes in dvc.lock
-        uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-          commit_message: Commit changes in dvc.lock
-          file_pattern: dvc.lock
+        uses: stefanzweifel/git-auto-commit-action@v5 with:
+          commit_message: Commit changes in dvc.lock file_pattern: dvc.lock
       - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
+        uses: actions/setup-node@v4 with:
           node-version: 20
       - name: Setup CML
-        uses: iterative/setup-cml@v2
-        with:
-          version: "0.20.0"
+        uses: iterative/setup-cml@v2 with:
+          version: '0.20.0'
       - name: Create CML report
         env:
           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -64,12 +91,12 @@ jobs:
           echo "# Experiment Report (${{ github.sha }})" >> report.md
 
           # Compare parameters to main branch
-          echo "## Params workflow vs. main" >> report.md
-          dvc params diff main --md >> report.md
+          echo "## Params workflow vs. main" >> report.md dvc params diff main --md >>
+          report.md
 
           # Compare metrics to main branch
-          echo "## Metrics workflow vs. main" >> report.md
-          dvc metrics diff main --md >> report.md
+          echo "## Metrics workflow vs. main" >> report.md dvc metrics diff main --md >>
+          report.md
 
           # Compare plots (images) to main branch
           dvc plots diff main
@@ -78,75 +105,98 @@ jobs:
           echo "## Plots" >> report.md
 
           # Create training history plot
-          echo "### Training History" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_training_history.png "Training History")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_training_history.png "Training History")' >> report.md
+          echo "### Training History" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_training_history.png "Training History")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_training_history.png "Training History")'
+          >> report.md
 
           # Create predictions preview
-          echo "### Predictions Preview" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md
+          echo "### Predictions Preview" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_pred_preview.png "Predictions Preview")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_pred_preview.png "Predictions Preview")'
+          >> report.md
 
           # Create confusion matrix
-          echo "### Confusion Matrix" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md
+          echo "### Confusion Matrix" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_confusion_matrix.png "Confusion Matrix")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_confusion_matrix.png "Confusion Matrix")'
+          >> report.md
 
           # Publish the CML report
           cml comment update --target=pr --publish report.md
   publish-and-deploy:
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
-    steps:
+    if: github.ref == 'refs/heads/main' steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.11"
-          cache: pip
+        uses: actions/setup-python@v5 with:
+          python-version: '3.11' cache: pip
       - name: Install dependencies
         run: pip install --requirement requirements-freeze.txt
       - name: Login to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
-          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
+        uses: google-github-actions/auth@v2 with:
+          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
       - name: Check model
         run: dvc repro --pull
       - name: Log in to the Container registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}
-          username: _json_key
-          password: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
+        uses: docker/login-action@v3 with:
+          registry:
+          ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }} username: _json_key password: ${{
+          secrets.GOOGLE_SERVICE_ACCOUNT _KEY }}
       - name: Import the BentoML model
-        run: bentoml models import model/celestial_bodies_classifier_model.bentomodel
+        run: bentoml models import model/celestial_bodies_classifier _model.bentomodel
       - name: Build the BentoML model artifact
         run: bentoml build src
       - name: Containerize and publish the BentoML model artifact Docker image
         run: |
           # Containerize the Bento
           bentoml containerize celestial_bodies_classifier:latest \
-            --image-tag ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/celestial-bodies-classifier:latest \
-            --image-tag ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/celestial-bodies-classifier:${{ github.sha }}
+            --image-tag
+            ${{ secrets.GCP_CONTAINER_REGISTRY _HOST }}/celestial-bodies-classifier:latest \ --image-tag ${{
+            secrets.GCP_CONTAINER_REGISTRY _HOST }}/celestial-bodies-classifier:${{
+            github.sha }}
           # Push the container to the Container Registry
-          docker push --all-tags ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/celestial-bodies-classifier
+          docker push --all-tags ${{ secrets.GCP_CONTAINER_REGISTRY _HOST
+          }}/celestial-bodies-classifier
       - name: Get Google Cloud's Kubernetes credentials
-        uses: google-github-actions/get-gke-credentials@v2
-        with:
-          cluster_name: ${{ secrets.GCP_K8S_CLUSTER_NAME }}
-          location: ${{ secrets.GCP_K8S_CLUSTER_ZONE }}
+        uses: google-github-actions/get-gke-credentials@v2 with:
+          cluster_name: ${{ secrets.GCP_K8S _CLUSTER_NAME }} location: ${{
+          secrets.GCP_K8S_CLUSTER _ZONE }}
       - name: Update the Kubernetes deployment
         run: |
-          yq -i '.spec.template.spec.containers[0].image = "${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/celestial-bodies-classifier:${{ github.sha }}"' kubernetes/deployment.yaml
+          yq -i '.spec.template.spec.containers[0].image =
+          "${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/celestial-bodies-classifier:${{
+          github.sha }}"' kubernetes/deployment.yaml
       - name: Deploy the model on Kubernetes
         run: |
           kubectl apply \
             -f kubernetes/deployment.yaml \
             -f kubernetes/service.yaml
+  cleanup-runner:
+    needs: train-and-report
+    runs-on: [self-hosted, base-runner]
+    # Run this job if the event is a pull request and regardless of whether the previous job failed or was cancelled
+    if: github.event_name == 'pull_request' && (success() || failure() || cancelled())
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Set up GCloud SDK
+        uses: google-github-actions/setup-gcloud@v2 with:
+          version: '>= 494.0.0'
+      - name: Install kubectl
+        run: |
+          gcloud components install kubectl
+      - name: Install gke-gcloud-auth-plugin
+        run: |
+          gcloud components install gke-gcloud-auth-plugin
+      - name: Cleanup runner on Kubernetes
+        env:
+          KUBECONFIG_DATA: ${{ secrets.GCP_K8S_KUBECONFIG }}
+        run: |
+          echo
+          "$KUBECONFIG_DATA" > kubeconfig export KUBECONFIG=kubeconfig export GITHUB_RUN_ID="${{
+          github.run_id }}" envsubst < kubernetes/runner-gpu.yaml | kubectl delete --wait=false -f -
